### PR TITLE
InfoLoggerContext::refresh should not query again quantities that cannot (reasonably) change

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by sy-c** [comment]
@ktf what problem are you trying to solve? Please open a JIRA ticket.

**Comment by ktf** [comment]
The JIRA ticket is https://alice.its.cern.ch/jira/browse/O2-2893

**Comment by ktf** [comment]
Actual issue solved in a different / better manner in Monitoring.

**Comment by sy-c** [comment]
I was going to comment that the cause is in monitoring , not in infologger.

**Pull request closed without merging**
